import { SetlistItem, WaveformMarker, MARKER_TYPE_COLORS } from '../store'

interface CueSheetOptions {
  presetName: string
  setlist: SetlistItem[]
  markers: Record<string, WaveformMarker[]>
  fps: number
}

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

function formatTime(sec: number): string {
  const h = Math.floor(sec / 3600)
  const m = Math.floor((sec % 3600) / 60)
  const s = Math.floor(sec % 60)
  if (h > 0) return `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`
  return `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`
}

/**
 * Generate HTML cue sheet and use Electron's printToPDF for CJK-safe PDF output.
 * Returns the HTML string; caller passes it to main process via IPC.
 */
export function buildCueSheetHtml(options: CueSheetOptions): string {
  const { presetName, setlist, markers, fps } = options
  const date = new Date().toLocaleDateString() + ' ' + new Date().toLocaleTimeString()

  let body = ''

  for (let i = 0; i < setlist.length; i++) {
    const song = setlist[i]
    const songMarkers = [...(markers[song.path] ?? [])].sort((a, b) => a.time - b.time)
    const songCues = (song.midiCues ?? []).filter(c => c.enabled)

    body += `<div class="song-header">${i + 1}. ${esc(song.name)}`
    if (song.notes) body += `<span class="notes">${esc(song.notes)}</span>`
    body += `</div>`

    if (songMarkers.length > 0) {
      body += `<div class="section-label">MARKERS</div><table>`
      for (const m of songMarkers) {
        const color = MARKER_TYPE_COLORS[m.type ?? 'custom']
        const typeLabel = (m.type ?? 'custom').toUpperCase()
        body += `<tr><td class="time">${formatTime(m.time)}</td><td style="color:${color}">${typeLabel}</td><td>${esc(m.label || '')}</td></tr>`
      }
      body += `</table>`
    }

    if (songCues.length > 0) {
      body += `<div class="section-label">MIDI CUES</div><table>`
      for (const cue of songCues) {
        const msgType = cue.messageType === 'program-change' ? 'PC'
          : cue.messageType === 'note-on' ? 'NOTE' : 'CC'
        body += `<tr><td class="time">${cue.triggerTimecode}</td><td class="midi">${msgType} ch${cue.channel} #${cue.data1}${cue.data2 !== undefined ? ` v${cue.data2}` : ''}</td><td>${esc(cue.label || '')}</td></tr>`
      }
      body += `</table>`
    }
  }

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
    body { font-family: -apple-system, 'Segoe UI', 'Microsoft JhengHei', 'PingFang TC', sans-serif; font-size: 11px; color: #222; margin: 20px 24px; }
    h1 { font-size: 18px; margin: 0 0 4px; }
    .meta { color: #888; font-size: 9px; margin-bottom: 16px; display: flex; justify-content: space-between; }
    .song-header { background: #1e1e1e; color: #fff; font-size: 13px; font-weight: 700; padding: 4px 8px; margin: 12px 0 4px; border-radius: 3px; display: flex; justify-content: space-between; }
    .song-header .notes { font-weight: 400; font-style: italic; font-size: 10px; color: #aaa; }
    .section-label { font-size: 9px; font-weight: 700; color: #888; margin: 6px 0 2px 4px; text-transform: uppercase; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 4px; }
    td { padding: 2px 6px; font-size: 10px; border-bottom: 1px solid #eee; }
    .time { width: 60px; font-family: monospace; color: #333; }
    .midi { color: #0096c8; }
    .footer { margin-top: 24px; font-size: 8px; color: #aaa; }
  </style></head><body>
    <h1>LTCast Cue Sheet — ${esc(presetName || 'Untitled')}</h1>
    <div class="meta"><span>${date}</span><span>${fps} fps</span></div>
    ${body}
    <div class="footer">Generated by LTCast</div>
  </body></html>`
}
